sudo: false

branches:
   except: /\+$/

language: node_js
node_js:
 - "node"
 - "4.2"
 - "0.12"
 - "0.10"

env:
   matrix:
    - UNIT=yes # dummy
    - BATS=yes
   #- RULEBOOK=yes
   global:
    - RULEBOOK=no # Pending completion of the queueless reactor!
    - CXX=g++-4.8
addons:
   apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-4.8


before_install:
 - case "$(npm --version)" in 1.*) npm install -g npm ;; esac
 - npm run-script ci -- --prep
 - export PATH="$PATH:$HOME/bats/bin/"

script:
 - npm run-script ci -- --test

after_success:
 - npm run-script ci -- --after

cache:
   directories:
    - node_modules
    - $HOME/bats


notifications:
   email: false
   irc:
      skip_join: true
      on_success: never
      on_failure: change
      channels:
       - "chat.freenode.net#ELLIOTTCABLE"
       - "chat.freenode.net#Paws.Nucleus"
      template:
       - "%{repository_name}/%{branch} @%{commit} %{author}: #%{build_number} %{message}"
       - "(Details: %{build_url})"
   slack:
      secure: "KTSaXaGAug+R8boN522JxPVXQaFiAKyebVvANcRGRCJPajEz12Dd3jo8aoE4r8zVFuuHUs8gQsOJoAu3w2j5FJo1ECq5OioPQqtYX7nJ6brtf/zVA2VTHmFueTeialOkNabhHJx+2Eh4J7JPVIb7MiLzaKqSLWHKHoB48HMaTCE="
